### ISSUE TITLE
User Identification / User <-> IP Mapping

### ISSUE THREAD

**Issue by MysticRyuujin** [PaloAltoNetworks/gridmeld#1]
As far as I can tell the localDB is configured to hold both the sgt and the user. But how do we get the PA to use this data for User/IP Mappings? Is it possible?

**Comment by kevinsteves** [comment]
The ideal case would be to have a MineMeld output node that would
publish "ip-user" mappings (show user ip-user-mapping) to PAN-OS.
However that does not exist today.

You can publish these as registered-ip objects with the user as a tag.
With the default session processing policy, the userName field is
mapped to the localDB "user" attribute.  Your dagPusherNg prototype can
use a config of { "tag_attributes": ["sgt", "user"] } which will add
user as a tag if it exists.
